import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { TopNav, HeadTitle, ListVehicles, VehicleInfo, Body, MainDiv, DetailsInfo, TitleDiv, LIListVehicles } from '../styles/styles'
import { useState, useEffect } from 'react'
import {Modal} from '../components/Modal'
import axios from 'axios'

let API = process.env.localAPI

export default function Home() {

  const [showModal, setShowModal] = useState(false)
  const [veiculos, setVeiculos] = useState([])
  const [vehicleObj, setVehicleObj] = useState()

  const [search, setSearch] = useState("")

  const [clicados, setClicados] = useState([])
  const [cor, setCor] = useState("white")

  const [clicado, setClicado] = useState(false)

  useEffect(() => {

        axios.get(`${API}/veiculos`).then(function (response) {
            setVeiculos(response.data.veiculos)
            console.log(veiculos);
        }).catch(function (error) {
            console.log("Erro: " + error);
        })

    }, [])

  const handleClick = (event, veiculo) => {

    if (clicados.includes(veiculo.id)){
      
      let index = clicados.indexOf(veiculo.id)
      clicados.splice(index, 1)
      console.log(clicados);
    } else {
      clicados.push(veiculo.id)
      veiculo.bg = "#A1A2A0"
    }
    setVehicleObj(veiculo)
    
    

  }

  return (
    <MainDiv>

<Modal showModal={showModal} setShowModal={setShowModal}/>

      <Head>
        <title>Teste Fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet"></link>
      </Head>

      <main>
        <TopNav>
          <section>
            <span className="material-icons-outlined">
              water_drop
            </span>
            <a>FULLSTACK</a>
            
          </section>
          <input 
            onKeyUp={() => {
              axios.get(`${API}/veiculos/find?q=${search}`).then(function (response) {
                setVeiculos(response.data.veiculo)
                console.log(veiculos);
              }).catch(function (error) {
                console.log("Erro: " + error);
            })
            }}
            value={search}
            placeholder="Busca por um veículo"
            onChange={e => setSearch(e.target.value)} 
          />
          
        </TopNav>
        
        <HeadTitle>
        
          <a>VEÍCULO</a>

          <span onClick={() => setShowModal(!showModal)} className="material-icons-outlined">
              add_circle
            </span>
          
        </HeadTitle>
        
        <br />
        <TitleDiv>
          <a>Lista de veículos</a><a>Detalhes</a>
        </TitleDiv>
        
        <Body>
        <ListVehicles>

          {
            veiculos.map(veiculo => {
              let sold
              //#A1A2A0
              //(event => handleClick(event, veiculo))
              veiculo.vendido ? sold = "#189c6c" : "#1D7555"
              return <LIListVehicles background={veiculo.bg} cor={sold} key={veiculo.id} onClick={() => setVehicleObj(veiculo)}>

                

                <section>
                  {veiculo.marca}
                  <br />
                  <a>{veiculo.veiculo}</a>
                  <br />
                  <span>{veiculo.ano}</span>
                  <br />
                </section>

                <div>
                  <span className="material-icons">
                    sell
                  </span>
                </div>
              </LIListVehicles>

            })
          }

        </ListVehicles>

        <VehicleInfo>
          

        { vehicleObj ? <section>
          
          <p>{vehicleObj.veiculo}</p>
          <DetailsInfo>
            <a>Marca<br /><span>{vehicleObj.marca}</span></a>
            <a>Ano<br /><span>{vehicleObj.ano}</span></a>
          </DetailsInfo>
          <br />
          <a>
          {vehicleObj.descricao}
          </a>
          <br /><br /><br />
        </section> : <div>Escolha um veículo no menu à esquerda.</div> }

        <div>
          <button>
            <span className="material-icons">
              edit
            </span>
              <a>EDITAR</a>
          </button>
          <span className="material-icons">
            sell
          </span>
        </div>

        </VehicleInfo>
        </Body>
      </main>

      
      
    </MainDiv>
  )
}
